repos:
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.2.0
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']
- repo: local
  hooks:
    - id: eslint
      name: Run ESLint
      entry: npm run lint:fix
      language: system
      types: [javascript]