repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']

  - repo: local
    hooks:
      - id: eslint-fix
        name: ES Lint with neostandard config
        entry: npm run lint:fix
        language: node