services:
  template-node-express-backend:
    build:
      target: development
    image: tempalte-node-express-backend-development
    container_name: template-node-express-backend-development
    ports:
      - "3000:3000"
      - "9000:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json