#!/usr/bin/env bash

if [ -z "$(docker network ls --filter name=^ch-tab$ --format={{.Name}})" ]; then
  echo "Creating node-express-template Docker network"
  docker network create node-express-template
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker-compose down

docker-compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  -f docker-compose.link.yaml \
  up $@